[workspace]
members = [
    ".",
    "crates/app",
    "crates/domain",
    "crates/feat",
    "crates/infra",
    "crates/platform",
    "crates/shared",
    "crates/ui",
    "crates/utils",
]
resolver = "3"

[package]
name = "gigu"
version = "0.1.0"
edition = "2024"

[dependencies]
app = { path = "crates/app" }
domain = { path = "crates/domain" }
feat = { package = "feat", path = "crates/feat" }
infra = { path = "crates/infra" }
platform = { path = "crates/platform" }
shared = { path = "crates/shared" }
ui = { path = "crates/ui" }
utils = { path = "crates/utils" }
makepad-widgets = { git = "https://github.com/makepad/makepad.git", branch = "dev", features = ["maps"] }
